# The Mechanism of Learning

### Loading Libraries

In [4]:
# Numerical Computing
import numpy as np

# Data Manipulation
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Iterate Optimization
# from tqdm.autonotebook import tqdm
from tqdm import tqdm

# PyTorch
import torch

In [5]:
# Visualization Performance Set-Up
%matplotlib inline
import matplotlib_inline.backend_inline

matplotlib_inline.backend_inline.set_matplotlib_formats('png', 'pdf')

### The World as A Tensor

In [6]:
torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1, 2, 3, 4])
torch_matrix = torch.tensor([[1, 2,],
                             [3, 4,],
                             [5, 6,], 
                             [7, 8,]])

torch_tensor3d = torch.tensor([
                            [
                            [ 1,  2,  3], 
                            [ 4,  5,  6],
                            ],
                            [
                            [ 7,  8,  9], 
                            [10, 11, 12],
                            ],
                            [
                            [13, 14, 15], 
                            [16, 17, 18],
                            ],
                            [
                            [19, 20, 21], 
                            [22, 23, 24],
                            ]
                              ])

In [7]:
# Getting tensor's shapes
print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_matrix.shape)
print(torch_tensor3d.shape)

torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


In [8]:
# NumPy Approach as follow:
x_np = np.random.random((4,4))
print(x_np)

[[0.43084198 0.19174837 0.15720407 0.03864828]
 [0.76068032 0.88094139 0.99762218 0.10706282]
 [0.41023892 0.02347961 0.17536861 0.72719724]
 [0.09254272 0.34020975 0.10861416 0.51437882]]


In [9]:
# Numpy on Tensors:
x_pt = torch.tensor(x_np)
print(x_pt)

tensor([[0.4308, 0.1917, 0.1572, 0.0386],
        [0.7607, 0.8809, 0.9976, 0.1071],
        [0.4102, 0.0235, 0.1754, 0.7272],
        [0.0925, 0.3402, 0.1086, 0.5144]], dtype=torch.float64)
